name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env: 
        CLOUD_HOSTNAME: ${{ vars.CLOUD_HOSTNAME }}
        CLOUD_USERNAME: ${{ vars.CLOUD_USERNAME }}
        CLOUD_SSH_KEY: ${{ secrets.CLOUD_SSH_KEY }}
      run: ls -la 
    # - run: docker build . --file Dockerfile --tag userdb:$(date +%s)
    - run: docker image ls
    - run: ssh -o StrictHostKeyChecking=no $CLOUD_USERNAME@$CLOUD_HOSTNAME "ls -la "
  
